name: zupzup Backend prod server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    # 테스트용 Mysql DB 컨테이너 생성
    services:
      mysql-test-db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test135
          MYSQL_DATABASE: zupzup_test_db
        ports:
          - 3307:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 레포지토리에서 프로젝트 파일 가져오기
        uses: actions/checkout@v4

      - name: github-actions JDK 21 설정
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 설정
        uses: gradle/actions/setup-gradle@v3

      - name: 실행 권한 부여
        run: chmod +x gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: EC2에 JAR 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/libs/*SNAPSHOT.jar,script/deploy.sh"
          target: "/home/ubuntu/zupzup/deploy"
          overwrite: true

      - name: EC2에서 배포 스크립트 파일 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export DB_HOST='${{ secrets.DB_HOST }}'
            export DB_USERNAME='${{ secrets.DB_USERNAME }}'
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            
            export AWS_S3_ACCESS_KEY='${{ secrets.AWS_S3_ACCESS_KEY }}'
            export AWS_S3_SECRET_ACCESS_KEY='${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}'
            export AWS_S3_BUCKET_NAME='${{ secrets.AWS_S3_BUCKET_NAME }}'
            
            export ACCESS_TOKEN_SECRET_KEY='${{ secrets.ACCESS_TOKEN_SECRET_KEY }}'
            export ACCESS_TOKEN_EXPIRATION='${{ secrets.ACCESS_TOKEN_EXPIRATION }}'
            
            export STUDENT_VERIFICATION_SESSION_TIME='${{ secrets.STUDENT_VERIFICATION_SESSION_TIME }}'
            
            chmod +x /home/ubuntu/zupzup/deploy/script/deploy.sh
            
            /home/ubuntu/deploy/zupzup/deploy/script/deploy.sh
            









